### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by mabeljarsdel** [mishadovhiy/Budget-Tracker#1]
Hi @mishadovhiy,

Sorry for opening a case here.

I've analysed your website, and it looks great. Is there a way to get the source code of it?

best,
Mabel

**Comment by mabeljarsdel** [comment]
hahlandos

**Comment by mishadovhiy** [comment]
Hello, I'm deeply sorry, honestly, that I didn't reply you earlier
I didn't see issue, wasn't using gidhub earlier too often

and when i saw issue i thought that you question is not relevant anymore, it was too long time since you wrote that issue

I'm sorry, i really thought it's not relevant

i was honestly happy that you like my website, it's the best compliment that developer could receive (I'm impressed by the amount of work you have, and the technologies you've achieved in your own projects and collaborations)

But do you think that i'm hahlandos? that confuses me and i hope that you just offended by not responding to your issue
and you think that Budget Tracker is a shit or ok?))) i could share my code maybe if you serious, but the code is really a shit on my website))

i really hope that we could handle that and i'm sorry to hear it about my work, and it made me curious if you serious that it's shit(
